version: latest

services:
  music-shop:
    build: ./
    command: ./music-shop
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=pass

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432